package com.example.demo.mapper;

import com.example.demo.entity.ChatEntity;


import java.util.List;

public interface ChatMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insert(ChatEntity entity);




    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    List<ChatEntity> selectAll(ChatEntity entity);





}
