package com.example.demo.mapper;

import com.example.demo.entity.CollectionEntity;
import com.example.demo.entity.CommentEntity;
import com.example.demo.entity.HotelEntity;


import java.util.HashMap;
import java.util.List;

public interface CollectionMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insert(CollectionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    CollectionEntity selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    List<HashMap> selectAll(CollectionEntity entity);





}
