package com.example.demo.mapper;

import com.example.demo.entity.CommentEntity;
import com.example.demo.entity.HotelEntity;


import java.util.List;

public interface HotelMapper {



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    HotelEntity selectByPrimaryKey(Integer id);



    int insert(HotelEntity record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    List<HotelEntity> selectAll1();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HotelEntity record);


}
