package com.example.demo.mapper;

import com.example.demo.entity.UserEntity;

import java.util.ArrayList;

public interface UserMapper {



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insert(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    UserEntity selectByPrimaryKey(String account);


    ArrayList<UserEntity> selectAll();


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserEntity record);



}
